# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Frameo Control Backend"
version: "0.1.0"
slug: "frameo_control"
description: "Backend service to control a Frameo device via ADB over USB or Network."
url: "https://github.com/HunorLaczko/ha-frameo-control-addon/tree/main/frameo_control"
arch:
  - aarch64
  - amd64
  - armv7
init: false
icon: "mdi:image-frame"
# Grant access to the host's USB devices
usb: true
# Use the host's network stack directly
host_network: true
# Expose the API port to Home Assistant
ports:
  "5000/tcp": null
options: {}
schema: {}
#image: "ghcr.io/hunorlaczko/{arch}-addon-frameo-control"
